# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detect/v1/detect.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'detect/v1/detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65tect/v1/detect.proto\x12\tdetect.v1\"(\n\x12\x41nalyzeFoodRequest\x12\x12\n\nobject_key\x18\x01 \x01(\t\"B\n\x08\x46oodItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x14\n\x0c\x63\x61lories_est\x18\x03 \x01(\x02\"G\n\x13\x41nalyzeFoodResponse\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.detect.v1.FoodItem\x12\x0c\n\x04note\x18\x02 \x01(\t2a\n\x11\x46oodDetectService\x12L\n\x0b\x41nalyzeFood\x12\x1d.detect.v1.AnalyzeFoodRequest\x1a\x1e.detect.v1.AnalyzeFoodResponseB*Z(fooder-backend/gen/go/detect/v1;detectv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detect.v1.detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(fooder-backend/gen/go/detect/v1;detectv1'
  _globals['_ANALYZEFOODREQUEST']._serialized_start=37
  _globals['_ANALYZEFOODREQUEST']._serialized_end=77
  _globals['_FOODITEM']._serialized_start=79
  _globals['_FOODITEM']._serialized_end=145
  _globals['_ANALYZEFOODRESPONSE']._serialized_start=147
  _globals['_ANALYZEFOODRESPONSE']._serialized_end=218
  _globals['_FOODDETECTSERVICE']._serialized_start=220
  _globals['_FOODDETECTSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
